### ISSUE TITLE
make ring.middleware.cors match the spec

### ISSUE THREAD

**Issue by lancepantz** [geni/geni-gedcom#3]
the spec at http://www.w3.org/TR/cors/

**Comment by lancepantz** [comment]
@Raynes I released 0.0.7 to clojars, note that `:access-control-allow-methods [:get :post]` is now required as in the docstring

**Comment by lancepantz** [comment]
@raynes that is ring-cors-0.0.7.jar

**Comment by lancepantz** [comment]
I'll actually probably take out the allow-methods stuff tonight actually, there's no point in it, i just got obsessed with the spec

**Comment by lancepantz** [comment]
nevermind, talked this out with @ninjudd and @amalloy they talked me into leaving it

**Comment by briangonzalez** [comment]
@lancepantz should CORS be working now?
