### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by aurels** [geni/geni-gedcom#8]
Hello,

This is not an issue but I could not find another place to post. Feel free to redirect me to the right spot.

I would like to try to use your project but I'm not familiar with closure at all.  Would you mind adding a section in the README with quick start steps to install the dependencies and start the app ?

Thanks,

Aurels

**Comment by ninjudd** [comment]
@Raynes can you take care of this?

**Comment by Raynes** [comment]
Yep. I love writing documentation. I'll get a guide going in the next day or so.

**Comment by aurels** [comment]
Thanks guys ;-)

**Comment by Raynes** [comment]
@aureis I've got this on my TODO list for Monday. Really busy with last minute moving stuff. Hope that's alright.

**Comment by aurels** [comment]
No problems, thanks !

**Comment by Raynes** [comment]
@aurels Just added instructions on getting the importer going. Let me know if they're sufficient.

**Comment by aurels** [comment]
Thanks, I'll try it out today when I am able and I'll let you know my eventual issues ;-)

**Comment by aurels** [comment]
Hello,

I can build and start the project without any trouble at all !

On the other side, I can't find the way to get an access token.  There isn't such a "Get Access Token" link/button on the API explorer page.  Google doesn't help me. Do I have to activate something on my account ?

Thanks.

**Comment by Raynes** [comment]
Right, you probably need to register an app. I'll update the instructions in a few.

**Comment by Raynes** [comment]
Updated. Let me know if that works out.

**Comment by aurels** [comment]
Raynes,

After reading you update I'm able to get a token ;-)

I'm now stuck at the step of the gedcom file upload.  When I upload it, it does nothing for dozens of seconds.  I then get a JS error in the console : 

```
Failed to load resource: Resource failed to load http://qa.geni.com:9255/geni-gedcom/upload
Uncaught SyntaxError: Unexpected end of input
```

Do you think my ged file is broken ?  It comes from MacFamilyTree and I can successfully import it in other software. I'm probably missing something here.

Btw, do I need to use the master branch or develop ?

**Comment by Raynes** [comment]
I was accidentally pushing against master until this last push. Make sure you've got the latest develop. I fixed that yesterday.

**Comment by aurels** [comment]
Awesome it works.  Many thanks to you for your help.

**Comment by Raynes** [comment]
No problem! If you ever have any other issues, let us know.
